<?php

namespace Core\Resources;

use Core\Abstracts\Resources\CoreResource;

class UserResource extends CoreResource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
